---
title: "About Me"
description: |
  Where I've been and where I'm going
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am a first-year master’s student at Bren School of Environmental Science & Management at UC Santa Barbara. I graduated from the University of California Berkeley (2012) with a Bachelor of Arts degree in Socio-cultural Anthropology and a Minor in Global Poverty and Practice. 

As a freshman in college I read *The Omnivore’s Dilemma* which spurred a fascination with the idea of food systems as a nexus point between the political, social, economic, and environmental spheres. Later I volunteered at a food justice non-profit that helped to deepened my understanding of the causes and consequences of disparate access to healthy food. After graduating, I worked for five years in the commercial real estate industry at CBRE, a Fortune 200 firm. Exposure to the economics of development and the importance of urban land use policy inspired me to learn more about the interaction between the built environment, human ecology, and social-environmental outcomes. After enrolling in a permaculture design course in 2018, I was introduced to systems science and the trade-offs of natural resource use and ecosystem management. These experiences led me to pursue an Environmental Science and Management degree at Bren, where I am specializing in the Economics and Politics of the Environment. 

My research interests center on the intersections between environmental policy, social justice, and sustainable development, as well as the environmental impacts of different practices in US Agriculture. I want to explore how different impact analysis tools can aid in developing effective environmental solutions, and the role that science communication can play in achieving support for, and adoption of, those solutions.